" make unix (NL) the default file format
set ff=unix

" always show the status line
set laststatus=2

" make tab stop (tab width in spaces) smaller
"set ts=4
set tabstop=8
set softtabstop=4

" make shift width (spaces for indenting << >>) smaller
"set sw=4
set shiftwidth=4

" syntax highlighting in color
syntax enable
syntax on

" show the ruler by default
set ruler

" highlight all matches for last used search pattern
"set hls
set hlsearch

" automatic indenting
set ai

" smart indenting
set si

" ignore case when searching
set ignorecase
set smartcase

" show matching brackets when text indicator is over them
set showmatch

" no sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set expandtab
set smarttab

" sets how many lines of history VIM has to remember
set history=750

set showmode
set autoindent
filetype on
filetype indent on
filetype plugin on

"Run pyflakes on files after you save them
au BufWritePost *.py !pyflakes % 
